# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
        repository: '465731220541.dkr.ecr.us-east-2.amazonaws.com/hello_world_luis'

    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws_connections'
        regionName: 'us-east-2'
        imageSource: 'imagename'
        sourceImageName: '465731220541.dkr.ecr.us-east-2.amazonaws.com/hello_world_luis'
        sourceImageTag: $(Build.BuildId)
        pushTag: 'latest'
        repositoryName: 'hello_world_luis'
  